name: Deploy To branch "domain" (with empty base href)
on:
  push:	
    branches:	
      - master

defaults:
  run:
    working-directory: ./

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm ci
      working-directory: ./
    - run: npm run build-deploy-as-root --if-present
      working-directory: ./
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: domain
        FOLDER: ./dist/easy2give-template-1
        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: invoke deployment hook
      uses: distributhor/workflow-webhook@v3.0.2
      env:
        webhook_url: ${{ vars.WEBHOOK_URL}}
