name: Deploy To gh-pages (with base href)
on:
  push:	
    branches:	
      - dev
      - shirley-template-1
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm ci
      working-directory: ./
    - name: update extras with key for invite code
      uses: jossef/action-set-json-field@v2.1
      with:
        file: ./src/environments/extra.json
        field: ApiKey_inviteCode
        value: ${{ secrets.ApiKey_inviteCode }}
    - name: update extras with key for update guest rsvp
      uses: jossef/action-set-json-field@v2.1
      with:
        file: ./src/environments/extra.json
        field: ApiKey_updateGuestRsvp
        value: ${{ secrets.ApiKey_updateGuestRsvp }}
    - run: npm run build-for-dev --if-present
      working-directory: ./
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: ./dist/shirley-template-1
        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
