name: Deploy To Self Branch
on:
  push:	
    branches:	
      - easy2give

defaults:
  run:
    working-directory: ./

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm ci
      working-directory: ./
    - run: npm run build --if-present
      working-directory: ./
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: ./dist/easy2give-template-1
        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
